menagerie:
  build: .
  command: /opt/menagerie/node_modules/.bin/pm2 start app.js --name "menagerie" -i 2 --no-daemon -- --prod
  links:
      - postgresql:pgsql01.menagerie.io
  environment:
    - DEBUG=*
    - NODE_AMQP_ENDPOINT=${NODE_AMQP_ENDPOINT}
    - NODE_HONEYBADGER_KEY=${NODE_HONEYBADGER_KEY}
    - NODE_AWS_ACCESS_KEY_ID=${NODE_AWS_ACCESS_KEY_ID}
    - NODE_AWS_SECRET_ACCESS_KEY=${NODE_AWS_SECRET_ACCESS_KEY}
  restart: always
  log_opt:
      max-size: "1g"
      max-file: "4"
  ports:
    - "1337:1337"
postgresql:
  image: postgres
  environment:
    - POSTGRESQL_DB=youtubeadl
    - POSTGRESQL_USER=youtubeadl
    - POSTGRESQL_PASSWORD=password
  # volumes:
    # - ~/dockerfiles/youtube-audio-dl/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"
  log_opt:
    max-size: "1g"
    max-file: "4"
